# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='phone',
        ),
    ]
